### ISSUE TITLE
Implement Solar Input Reader

### ISSUE THREAD

**Issue by john-chrosniak** [solarcaratuva/Rivanna2#102]
* Create SolarInputReader class that can read all analog inputs on solar board
* Look at ECUInputReader class for guidance
* Blocks #63

**Comment by edward-noe** [comment]
`uint16_t get_total_current()`
`uint16_t get_panel_voltage(int panel)`
`uint16_t get_panel_temp(int panel)`
`uint16_t get_panel_photo(int panel)`
