### ISSUE TITLE
Add tests for `CANInterface`

### ISSUE THREAD

**Issue by NripeshManandhar** [solarcaratuva/Rivanna2#12]
- [x] Initializing 
- [ ] rx_handler()
- [ ] tx_handler()

**Comment by ahmedh409** [comment]
- Each team uses its own structs to identify CAN messages (overrides Common>lib>CANParser>CANParser.h)
- test_can_interface.cpp uses methods from fakeit.hpp (https://github.com/eranpeer/FakeIt)
