### ISSUE TITLE
Research and finish CAN message definitions

### ISSUE THREAD

**Issue by john-chrosniak** [solarcaratuva/Rivanna2#27]
Need to research best ways to define CAN messages. Want to minimize amount of padding, size of messages, etc.

- [x] #47
- [x] Motor Messages
- [x] #58
- [x] #46

**Comment by edward-noe** [comment]
We need to define CAN structs based on [this spreadsheet](https://docs.google.com/spreadsheets/d/1ebnRxqcYQUPn0RJzo-r7umx5mBk81SM5VOVU08qPaks/edit#gid=0). (Let me know if you don't have access for some reason.) Each struct has a name (e.g. `SolarCurrent`) and a set of fields. Each field has a name (e.g. `total_current`) and a data type (e.g. `int16_t`). 

To define a CAN struct for a board, you should create or modify the CANStructs file for the board. For example, [this](https://github.com/solarcaratuva/Rivanna2/blob/master/PowerAux/include/PowerAuxCANStructs.h) is the CANStructs file for the PowerAux board.

When done, submit a PR to merge your changes into the `can-structs` branch.
