### ISSUE TITLE
Enable printing floats with printf

### ISSUE THREAD

**Issue by edward-noe** [solarcaratuva/Rivanna2#71]
Right now, `printf("%f\n", 1.0f)` prints `%f` instead of the actual number. [This link](https://techoverflow.net/2020/10/07/how-to-fix-mbed-printf-printing-literal-f-in-platformio/) describes a potential solution, but it did not work when I tried it.

**Comment by john-chrosniak** [comment]
If you have to write any functions to get printing working, you can put that in Common/lib/Printing/Printing.cpp

**Comment by edward-noe** [comment]
This can be done using the `printFloat` method defined in `Common/lib/Printing/Printing.h`.
